### ISSUE TITLE
Add sample contract that shows RSA signature verification.

### ISSUE THREAD

**Issue by razi-rais** [firoorg/solidity-BigNumber#1]
Please add a sample contract with code in solidity that demonstrate verification of RSA signatures.

**Comment by riordant** [comment]
This library provides the functions to build that but won't include it directly. I will likely develop a separate repo for signature verification soon. see this if you need this now https://github.com/adriamb/SolRsaVerify/blob/master/SolRsaVerify.sol

**Comment by riordant** [comment]
Added in commit: https://github.com/firoorg/solidity-BigNumber/commit/ca66e95ec3ef32250b0221076f7a10f0d8529bd8
