### ISSUE TITLE
bn_div

### ISSUE THREAD

**Issue by AHaliq** [firoorg/solidity-BigNumber#10]
Any chance for an actual bn_div computation function?

I'm using the library for non cryptographic purposes and need this function.

**Comment by riordant** [comment]
Div is far too expensive to compute on chain for values greater than the word size. In all cases it would be better for you to compute beforehand.
Could you show me how you want to use it?

**Comment by riordant** [comment]
Closing, please re-open if you want guidance on usage of the verify function.
