### ISSUE TITLE
Pinned solidity version in BigNumbers.sol

### ISSUE THREAD

**Issue by Schwartz10** [firoorg/solidity-BigNumber#15]
Hi there maintainers! Thanks for writing this solidity library.

Wondering what the rational is behind pinning the `0.8.17` solidity version in BigNumbers.sol, wheres `/utils/Crypto.sol` is using `^0.8.17`

Any danger in using a solidity version above `0.8.17`? I couldn't find any issues, but not sure if there's something i'm missing

**Comment by riordant** [comment]
Hi @Schwartz10 
no rationale, oversight really, should be `^0.8.17` 
happy to bump the version or review a PR for that.

**Comment by Schwartz10** [comment]
@riordant really appreciate the quick response! Here's a PR for your convenience https://github.com/firoorg/solidity-BigNumber/pull/16

**Comment by riordant** [comment]
Merged - if you have other suggestions for improvements would be more than happy to review :)
