### ISSUE TITLE
randomness_length is used before being defined

### ISSUE THREAD

**Issue by brainhub** [firoorg/solidity-BigNumber#2]
https://github.com/zcoinofficial/solidity-BigNumber/blob/5355ea7c6e942f613855c509ebd0d98afbe39ec7/contracts/MockBigNumber.sol#L81

81:      uint **offset** = (0x20 - ((**randomness_length**%0x20)==0 ? 0x20 : (**randomness_length**%0x20)));
82:      uint **randomness_length** = randomness_length_base + **offset**;

Unclear how to resolve this issue. Switching the lines will make the same problem apply to **offset**.

This doesn't compile with Solidity 0.5.0

**Comment by riordant** [comment]
Resolved in https://github.com/zcoinofficial/solidity-BigNumber/commit/2bddf04709f0e1ed649b37b5533264cef8c5cbfe
