### ISSUE TITLE
modular multiplication runs out of gas

### ISSUE THREAD

**Issue by shayanb** [firoorg/solidity-BigNumber#5]
Trying this code to calculate modular exponentiation, however in the below code `prepare_modexp` modular exponentiation works with the values x and p, but `modmul` modular multiplication runs out of gas.

```solidity
pragma solidity >=0.4.20 <0.6;

import "./BigNumber.sol";

/* 

 */

contract testmod {
  using BigNumber for *; 
  
  function test() public returns(bytes memory,bool,uint){
    BigNumber.instance memory g;
    BigNumber.instance memory p;
    BigNumber.instance memory x;

    g.val = hex"04";
    g.neg = false;
    g.bitlen = BigNumber.get_bit_length(g.val);

    p.val = hex"0800";
    p.neg = false;
    p.bitlen = BigNumber.get_bit_length(p.val);

    x.val = hex"03";
    x.neg = false;
    x.bitlen = BigNumber.get_bit_length(x.val);

    //BigNumber.instance memory res = g.modmul(x,p);
    BigNumber.instance memory res = g.prepare_modexp(x,p);

    return (res.val, res.neg, res.bitlen);
  }
```

I think the issue is with the for loop on line 140 in `bn_add()`, but not sure how to fix it:
https://github.com/zcoinofficial/solidity-BigNumber/blob/db0d6d298cee2d8974cb6ffa76659d96f3454150/contracts/BigNumber.sol#L140-L168

**Comment by elijahj19** [comment]
Any update? I am experiencing the exact same issue

**Comment by robmuth** [comment]
I'm not an expert for that library, but the inline comments say you shouldn't instantiate the struct directly. However, if you want to get it running that way, this should work:

```solidity
g.val = hex"0000000000000000000000000000000000000000000000000000000000000004";
p.val = hex"0000000000000000000000000000000000000000000000000000000000000800";
x.val = hex"0000000000000000000000000000000000000000000000000000000000000003";
```

Or you can use the ```BigNumber._new(val, neg, copy)``` function instead (```abi.encodePacked(...)``` converts the values to bytes):

```solidity
function test() public returns(bytes memory,bool,uint){
  BigNumber.instance memory g = BigNumber._new(abi.encodePacked(uint256(0x04)), false, false);
  BigNumber.instance memory p = BigNumber._new(abi.encodePacked(uint256(0x0800)), false, false);
  BigNumber.instance memory x = BigNumber._new(abi.encodePacked(uint256(0x03)), false, false);

  BigNumber.instance memory res = g.modmul(x, p);

  return (res.val, res.neg, res.bitlen);
}
```

Result of (4 * 3) mod 2048:

```
value: 0x000000000000000000000000000000000000000000000000000000000000000c (12)
negative: false
bitlen: 4
```

**Comment by evmcheb** [comment]
@robmuth both of those snippets produce an error on solidity v0.8

however, it works with solidity v0.5.17.

**Comment by evmcheb** [comment]
> @robmuth both of those snippets produce an error on solidity v0.8
> 
> however, it works with solidity v0.5.17.

to fix on solidity v0.8, wrap first loop of right_shift in an `unchecked{}` block

**Comment by riordant** [comment]
Hi, the library has been updated and this issue should be resolved.

**Comment by riordant** [comment]
Hi, a test case has been added for this particular case: https://github.com/firoorg/solidity-BigNumber/blob/master/test/BigNumbers.t.sol#L267
