### ISSUE TITLE
update contracts to work with solidity ^0.8.0

### ISSUE THREAD

**Issue by tdudz** [firoorg/solidity-BigNumber#6]
hi @riordant, as noted in a few of the other issues, this library doesn't work with solidity ^0.8.0 due to the addition of built-in safemath operations

are there any plans to update this repo to support latest solidity? this way a few of us wouldn't need to fork it. thanks!

**Comment by riordant** [comment]
Hey Tom, as of recently I am in in the process of updating the library.

**Comment by tdudz** [comment]
@riordant that's great to hear. do you have a rough estimate of when that will be pushed? thanks

**Comment by dionyziz** [comment]
Any updates on this?

**Comment by riordant** [comment]
Hi, the library has been updated to Solidity 0.8.16 and safemath operations handled, so this issue should be resolved.
