### ISSUE TITLE
LICENSE??

### ISSUE THREAD

**Issue by matsutakk** [firoorg/solidity-BigNumber#9]
Hi, thank you for great OSS. 

Maybe my question seems weird but I would like to know.

This repository says this is MIT license, but your solidity code says SPDX unlicense.

Could I use your code and upload my repository??

thank you.

**Comment by riordant** [comment]
Hi, the code will soon be moving to MIT license. you are free to use the code, but please be advised it is not yet audited. if you intend to use it in production level code the segments you use should be audited by a reputable firm.

**Comment by matsutakk** [comment]
Thank you for your reply!
